name: ♺ deploy 

on:
    workflow_call:
        inputs:
            env:
                description: 'Environment to deploy this branch to test|dev'
                required: true
                type: string

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            ENV: ${{ inputs.env }}
        steps:
            - run: echo "Running deployment on $ENV..."
     