name: On Push

on:
    push:
        branches:
            - master
        tags-ignore:
            - '**'
    
jobs:
    Build:
        uses: rehangit/gha/.github/workflows/build.yml@master
        with: 
          packages: 'a, b, c'
        secrets: inherit
