name: Tag deploy prod

on:
    push:
        branches-ignore:
            - '**'
        tags:
            - v[0-9]+.[0-9]+.[0-9]+

jobs:
    Check:
        runs-on: ubuntu-latest
        steps:
          - name: dump github
            run: echo ${{ toJson(github) }}

          - name: exit if not main
            if: github.event.base_ref != 'main'
            run: exit -1

    Deploy-prod:
        needs: [Check]
        uses: ./.github/workflows/deploy.yml
        with:
            env: prod
        secrets: inherit
