name: Tag deploy prod

on:
    push:
        branches-ignore:
            - '**'
        tags:
            - v[0-9]+.[0-9]+.[0-9]+

jobs:
    Deploy-prod:
        uses: ./.github/workflows/deploy.yml
        with:
            env: prod
        secrets: inherit
