name: Tag deploy prod

on:
    push:
        branches-ignore:
            - '**'
        tags:
            - v[0-9]+.[0-9]+.[0-9]+

jobs:
    Deploy-prod:
        runs-on: ubuntu-latest
        steps:
            - name: Stage tag check
              if: ${{ inputs.environment == 'prod' }}
              uses: rehangit/gha/actions/prod-checks@master

            - name: Deploy
              uses: ./.github/workflows/deploy.yml
              with:
                 env: prod
                 secrets: inherit
