name: Tag deploy prod

on:
    push:
        branches-ignore:
            - '**'
        tags:
            - v[0-9]+.[0-9]+.[0-9]+

jobs:
    ProdChecks:
        runs-on: ubuntu-latest
        steps:
          - uses: rehangit/gha/actions/prod-checks@master

    Deploy-prod:
        needs: [ProdChecks]
        uses: ./.github/workflows/deploy.yml
        with:
            env: prod
