name: Tag deploy prod

on:
    push:
        branches-ignore:
            - '**'
        tags:
            - v[0-9]+.[0-9]+.[0-9]+

jobs:
    Check:
        name: Exit if not on main branch
        runs-on: ubuntu-latest
        if: github.event.base_ref != 'main'
        steps:
          - run: exit -1

    Deploy-prod:
        needs: [Check]
        uses: ./.github/workflows/deploy.yml
        with:
            env: prod
        secrets: inherit
