name: Tag deploy prod

on:
    push:
        branches-ignore:
            - '**'
        tags:
            - v[0-9]+.[0-9]+.[0-9]+

jobs:
    Check:
        runs-on: ubuntu-latest
        steps:
          - name: dump github
            env:
              GITHUB_VAR: ${{ toJson(github) }}
            run: echo "$GITHUB_VAR"


          - name: exit if not main
            env:
              REF: ${{ github.event.base_ref }}
              MASTER: ${{ join(['ref', 'heads', github.event.repository.master_branch], '/') }}
            run: |
              echo REF=$REF
              echo MASTER=$MASTER
              if [ "$REF" != "${{MASTER}}" ]; then exit -1; fi

    Deploy-prod:
        needs: [Check]
        uses: ./.github/workflows/deploy.yml
        with:
            env: prod
        secrets: inherit
