name: Tag deploy prod

on:
    push:
        branches-ignore:
            - '**'
        tags:
            - v[0-9]+.[0-9]+.[0-9]+

jobs:
    ProdChecks:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            with:
              fetch-depth: 0
          - uses: rehangit/gha/.github/actions/prod-checks

    Deploy-prod:
        needs: [ProdChecks]
        uses: ./.github/workflows/deploy.yml
        with:
            env: prod
