name: Tag deploy prod

on:
    push:
        branches-ignore:
            - '**'
        tags:
            - v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+

jobs:
    Deploy-stage:
        uses: ./.github/workflows/deploy.yml
        with:
            env: stage
        secrets: inherit
